####################
###   .mocharc   ###
###   1105.1.0   ###
####################

# https://mochajs.org/#configuration-format
# https://mochajs.org/#command-line-usage

spec:
  - "dist/**/*.spec.js"
extension:
  - js
  - cjs
  - mjs
require: dist/_test/hooks.js # @OVERRIDE
