####################
###   .mocharc   ###
###   1107.1.0   ###
####################

# https://mochajs.org/#configuration-format
# https://mochajs.org/#command-line-usage

extension: [js]
require: dist-tests/index.js
spec: [dist-tests/**/*.spec.js]
