####################
###   .mocharc   ###
###   1107.0.0   ###
####################

# https://mochajs.org/#configuration-format
# https://mochajs.org/#command-line-usage

spec: [dist-tests/**/*.spec.js]
extension: [js]
require: dist-tests/hooks.js # @OVERRIDE
