# ##################
# #   .mocharc   ###
# #   1101.0.0   ###
# ##################

# https://mochajs.org/#configuration-format
# https://mochajs.org/#command-line-usage

require: dist/_test/hooks.js
spec:
  - "dist/**/*.spec.js"
extension:
  - js
  - cjs
  - mjs
color: true
