name: Azure Publish (${{env.environment}})
env:
  branch: &branch dev
  environment: *branch
on: { push: { branches: [*branch] } }
jobs:
  publish-dev:
    name: Build/Publish (${{env.environment}})
    environment:
      name: *environment
      url: https://${{vars.AZ_ACCOUNT}}.blob.core.windows.net/${{vars.AZ_CONTAINER}}/${{vars.PACKAGE}}.zip
    permissions: { contents: read }
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Install Node
        id: node
        uses: actions/setup-node@v4
        with: { node-version: 22 }
      - name: Install Dependencies
        id: ci
        run: npm ci
      - name: Build/Pack Distro
        id: build-pack
        run: npm run deploy
      - name: Zip Distro
        id: zip
        run: zip
          -r ${{vars.PACKAGE}}.zip
          ${{vars.PACKAGE}}
      - name: Publish to Azure
        id: publish
        uses: Azure/cli@v2
        with:
          azcliversion: 2.61.0
          inlineScript: az storage blob upload
            -c ${{vars.AZ_CONTAINER}}
            -f ${{vars.PACKAGE}}.zip
            -n ${{vars.PACKAGE}}.zip
            --overwrite true
            --account-name ${{vars.AZ_ACCOUNT}}
            --sas-token '${{secrets.AZ_CONTAINER_SAS_TOKEN}}'
